[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff", "basedpyright"]
formatter = { command = "ruff", args = ["format", "-"]}
auto-format = true
