---
github_dev_http:
  - junegunn/fzf
  - jhawthorn/fzy
  - asottile/babi
  - docker/compose
  - pypa/pipx

github_dev_ssh:
  - scwfri/serenity
  - scwfri/neovim
  - scwfri/es
  - scwfri/class
  - scwfri/compiler-explorer
  - scwfri/ray-tracer-5k
  - scwfri/natalie
  - scwfri/hackerrank
  - scwfri/flamenco
  - scwfri/pynvenv.nvim
  - scwri/go
  - scwfri/cpython
