brew_mac_formulas:
  - aider
  - anomalyco/tap/opencode
  - ansible-language-server
  - ast-grep
  - atuin
  - autoconf
  - automake
  - awscli
  - bash
  - bash-language-server
  - bat
  - bats
  - beads
  - bfs
  - btop
  - cargo-nextest
  - chicken
  - cloc
  - cmake
  - cmake-docs
  - colima
  - coreutils
  - csvlens
  - ctags
  - curl
  - difftastic
  - docker
  - docker-buildx
  - docker-completion
  - docker-compose
  - docker-credential-helper
  - dockerfile-language-server
  - dolt
  - duckdb
  - eksctl
  - emmylua_ls
  - eslint
  - eza
  - fd
  - ffmpeg
  - fish
  - fzf
  - gcc
  - gemini-cli
  - gettext
  - ghostscript
  - git
  - git-absorb
  - git-gui
  - git-lfs
  - gitlab-ci-local
  - glab
  - gnupg
  - gnutls
  - gopls
  - guile
  - hadolint
  - helm
  - helm-ls
  - helmfile
  - htop
  - httpie
  - imagemagick
  - jdtls
  - jless
  - jq
  - json5
  - jsonlint
  - just
  - k9s
  - kind
  - kubecolor
  - kubectx
  - kubernetes-cli
  - kustomize
  - libgccjit
  - libomp
  - llama.cpp
  - llvm
  - lua
  - lua-language-server
  - luajit
  - luarocks
  - markdownlint-cli
  - marksman
  - minikube
  - mise
  - ncdu
  - ninja
  - nx
  - opam
  - openjdk
  - opentofu
  - oven-sh/bun/bun
  - perl
  - pnpm
  - prettier
  - protobuf
  - rclone
  - ripgrep
  - ruby-build
  - ruff
  - rustup
  - sbcl
  - sd
  - shellcheck
  - sk
  - stern
  - stow
  - stylua
  - taplo
  - tectonic
  - terraform-ls
  - the_silver_searcher
  - tig
  - tmux
  - tofu-ls
  - tox
  - tree
  - tree-sitter
  - tree-sitter-cli
  - ts_query_ls
  - typescript-language-server
  - uv
  - vscode-langservers-extracted
  - vue-language-server
  - watch
  - watchexec
  - wcurl
  - wget
  - yaml-language-server
  - yamlfmt
  - yamllint
  - yq
  - zoxide
  - zsh
  - zsh-async
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting

brew_mac_casks:
  - 1password-cli
  - alt-tab
  - audacity
  - bartender
  - claude
  - claude-code
  - codex
  - docker-desktop
  - easy-move-plus-resize
  - ghostty@tip
  - google-cloud-sdk
  - hammerspoon
  - insomnia
  - karabiner-elements
  - maccy
  - ollama
  - opencode-desktop
  - openlens
  - rectangle
  - spotify
  - vlc
  - wireshark
  - zen
