#!/bin/sh

have() {
    command -v "$1" &> /dev/null
}

install_ansible() {
    have ansible || sudo dnf install -y ansible
}

install_homebrew() {
    if ! have "brew"; then
        sudo dnf group install -y 'Development Tools'
        sudo dnf install -y procps-ng curl file git libxcrypt-compat
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
}

run_playbook() {
    ansible-playbook -K ./linux.yml -i ./ansible_hosts
    ansible-galaxy collection install community.general
}

install_deps() {
    install_ansible
    install_homebrew
}

pre-commit install
install_deps
run_playbook
