#!/bin/sh

install_ansible() {
    command -v ansible-playbook > /dev/null || sudo dnf install -y ansible
}

run_playbook() {
    ansible-playbook -K ./linux.yml -i ./ansible_hosts
}

install_ansible
run_playbook
