---
- hosts: localhost
  connection: local
  roles:
    - role: packages
      tags: 
        - packages
    - role: dotfiles
      tags:
        - dotfiles
    - role: python
      tags:
        - python
    - role: other
      tags:
        - other
    # - role: flatpak
    #   tags:
    #     - flatpak
    # - role: git
    #   tags:
    #     - git
