---
- hosts: local
  environment:
    XDG_CONFIG_HOME: $HOME/.config
  roles:
    - role: meta
      tags:
        - meta
    - role: packages
      tags:
        - packages
    - role: dotfiles
      tags:
        - dotfiles
    - role: python
      tags:
        - python
    - role: other
      tags:
        - other
    - role: fonts
      tags:
        - fonts
    - role: flatpak
      tags:
        - flatpak
    # - role: git
    #   tags:
    #     - git
    - role: brew
      tags:
        - brew
        - homebrew
