# Increase from default value (256)
ulimit -n 10240

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$TMPDIR"

export ZSH_DATA_DIR=$XDG_DATA_HOME/zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export EMACS_VTERM_PATH=$XDG_CONFIG_DIR/emacs/straight/repos/emacs/libvterm
export GOPATH=$HOME/go
GOBIN=$GOPATH/bin
BREWSBIN=$HOMEBREW_PREFIX/sbin
BREWBIN=$HOMEBREW_PREFIX/bin
LUAROCKSBIN=$HOME/.luarocks/bin
PERL5BIN=$HOME/perl5/bin
USRLOCALBIN=/usr/local/bin
LOCALBIN=$HOME/.local/bin
PYTHON3_VENV_BIN=$HOME/.venv/venv/bin
OPENJDKBIIN=/opt/homebrew/opt/openjdk/bin
SCALA_COURSIER=$HOME/Library/Application\ Support/Coursier/bin

# set path and stuff
export PATH=$LOCALBIN:$BREWBIN:$BREWSBIN:$GOBIN:$PERL5BIN:$LUAROCKSBIN:$PATH:$USRLOCALBIN:$SCALA_COURSIER:$PYTHON3_VENV_BIN:$OPENJDKBIIN
# export PYTHONSTARTUP=$XDG_CONFIG_HOME/python/python_startup.py
export PERL5LIB=${PERL5LIB:=$HOME/perl5/lib/perl5}
export PERL_LOCAL_LIB_ROOT=${PERL_LOCAL_LIB_ROOT:=$HOME/perl5}
export PERL_MB_OPT=${PERL_MB_OPT:=--install_base \"$HOME/perl5\"}
export PERL_MM_OPT=${PERL_MM_OPT:=INSTALL_BASE=$HOME/perl5}

typeset -U path PATH
typeset -U fpath

if [ ! -d $ZSH_DATA_DIR ]; then
    mkdir $ZSH_DATA_DIR
fi
