---
- name: Install dnf packages
  become: true
  ansible.builtin.dnf:
    name:
      - bat
      - chicken
      - clang
      - clang-tools-extra
      - cmake
      - curl
      - fd-find
      - freetype-devel
      - fontconfig-devel
      - fzf
      - g++
      - gimp
      - git-core
      - gitk
      - guile
      - htop
      - java-11-openjdk-devel
      - kitty
      - libxcb-devel
      - libxkbcommon-devel
      - llvm
      - lua
      - nasm
      - neovim
      - ninja-build
      - perl-core
      - ripgrep
      - rsync
      - ruby-devel
      - ShellCheck
      - zig
      - zsh
      - util-linux-user
      - '@C Development Tools and Libraries'
      - '@virtualization'
      - '@Development Tools'
    state: present

- name: Ensure $XDG_CONFIG_HOME folder is created
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
    mode: '0775'

- name: Ensure $HOME/dev/utils folder is created
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dev/utils"
    state: directory
    mode: '0755'

- name: Ensure $HOME/.local/bin folder is created
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    mode: '0755'

- name: Git clone fzy
  ansible.builtin.git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: $HOME/dev/utils/fzy
    update: false

- name: Install fzy
  ansible.builtin.command:
    cmd: make
    chdir: $HOME/dev/utils/fzy
    creates: $HOME/dev/utils/fzy/fzy

- name: Symlink fzy to $HOME/.local/bin/fzy
  ansible.builtin.file:
    src: $HOME/dev/utils/fzy/fzy
    dest: $HOME/.local/bin/fzy
    state: link

- name: Check if rust is installed
  ansible.builtin.shell: command -v rustc
  register: cargo_exists
  ignore_errors: true
  tags:
    rust

- name: Install Rust
  ansible.builtin.shell: set -o pipefail && curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: cargo_exists is failed
