---
- name: Upgrade all dnf packages
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Install dnf packages
  become: yes
  dnf:
    name:
      - bat
      - chicken
      - clang
      - clang-tools-extra
      - cmake
      - curl
      - fd-find
      - fzf
      - gimp
      - git-core
      - gitk
      - guile
      - htop
      - java-11-openjdk-devel
      - kitty
      - llvm
      - llvm
      - lua
      - nasm
      - neovim
      - ninja-build
      - perl-core
      - ripgrep
      - rsync
      - ruby-devel
      - ShellCheck
      - zsh
      - util-linux-user
      - '@C Development Tools and Libraries'
      - '@virtualization'
      - '@Development Tools'
    state: latest

- name: Ensure $HOME/dev/utils folder is created
  command:
    cmd: mkdir -p $HOME/dev/utils
    creates: $HOME/dev/utils

- name: Git clone fzy
  git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: $HOME/dev/utils/fzy
    update: no

- name: Install fzy
  command:
    cmd: make
    chdir: $HOME/dev/utils/fzy
    creates: $HOME/dev/utils/fzy/fzy

- name: Symlink fzy to $HOME/.local/bin/fzy
  file:
    src: $HOME/dev/utils/fzy/fzy
    dest: $HOME/.local/bin/fzy
    state: link
