---
- name: Install dnf packages
  become: yes
  dnf:
    name:
      - bat
      - chicken
      - clang
      - clang-tools-extra
      - cmake
      - curl
      - fd-find
      - freetype-devel
      - fontconfig-devel
      - fzf
      - g++
      - gimp
      - git-core
      - gitk
      - guile
      - htop
      - java-11-openjdk-devel
      - kitty
      - libxcb-devel
      - libxkbcommon-devel
      - llvm
      - llvm
      - lua
      - nasm
      - neovim
      - ninja-build
      - perl-core
      - ripgrep
      - rsync
      - ruby-devel
      - ShellCheck
      - zsh
      - util-linux-user
      - '@C Development Tools and Libraries'
      - '@virtualization'
      - '@Development Tools'
    state: latest

- name: Ensure $XDG_CONFIG_HOME folder is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Ensure $HOME/dev/utils folder is created
  file:
    path: "{{ lookup('env', 'HOME') }}/dev/utils"
    state: directory

- name: Ensure $HOME/.local/bin folder is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: Git clone fzy
  git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: $HOME/dev/utils/fzy
    update: no

- name: Install fzy
  command:
    cmd: make
    chdir: $HOME/dev/utils/fzy
    creates: $HOME/dev/utils/fzy/fzy

- name: Symlink fzy to $HOME/.local/bin/fzy
  file:
    src: $HOME/dev/utils/fzy/fzy
    dest: $HOME/.local/bin/fzy
    state: link

- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    rust

- name: Download cargo installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
