---
- name: Install dnf packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ dnf_packages + dnf_group_packages }}"
  loop_control:
    label: "{{ item }}"

- name: Ensure $HOME/dev/utils folder is created
  command:
    cmd: mkdir -p $HOME/dev/utils
    creates: $HOME/dev/utils

- name: Git clone fzy
  git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: $HOME/dev/utils/fzy
    update: no

- name: Install fzy
  command:
    cmd: make
    chdir: $HOME/dev/utils/fzy
    creates: $HOME/dev/utils/fzy/fzy

- name: Symlink fzy to $HOME/.local/bin/fzy
  file:
    src: $HOME/dev/utils/fzy/fzy
    dest: $HOME/.local/bin/fzy
    state: link
