uv_tool_packages:
  - ansible-lint
  - ansible-dev-tools
  - beautysh
  - cython
  - git-filter-repo
  - ipython
  - mdformat
  - nbstripout
  - pre-commit
  - pudb
  - rstcheck
  - ruff
  - ty@latest
