vim.cmd('set runtimepath^=~/.vim')
vim.cmd('set runtimepath+=~/.vim/after')
vim.cmd('let &packpath = &runtimepath')

require('scwfri.utils')
require('scwfri.config')
require('pconfig')
require('scwfri.colors')
require('scwfri.keymap')
require('scwfri.funcs')
