- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ lookup('env', 'XDG_CONFIG_HOME') }}"
    - "{{ lookup('env', 'HOME') }}/scratch"
    - "{{ lookup('env', 'HOME') }}/bin"
    - "{{ lookup('env', 'HOME') }}/code"
    - "{{ lookup('env', 'HOME') }}/code/lib"
    - "{{ lookup('env', 'HOME') }}/code/personal"
    - "{{ lookup('env', 'HOME') }}/.local/bin"
- name: Symlink dotfiles
  ansible.builtin.shell: >
    stow --dotfiles alacritty asdfrc conda eslintrc fd fish ghostty git hammerspoon httpie jetbrains karabiner mise nvim ocamlinit pdbrc poetry psql python ripgrep ruff tmux vim wezterm yamllint zsh

  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
