---
- name: Install nvm
  command:
    cmd: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    creates: $XDG_CONFIG_HOME/nvm

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
    executable: "$XDG_CONFIG_HOME/nvm/versions/node/{{ node_version }}/bin/npm"
    state: present
  loop: "{{ npm_packages }}"
  loop_control:
    label: "{{ item }}"

- name: Install rbenv
  command:
    cmd: git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    creates: $HOME/.rbenv

- name: Create rbenv plugins dir
  command:
    cmd: mkdir -p $(rbenv root)/plugins
    creates: "{{ rbenv_root }}/plugins"

- name: Install ruby-build
  command:
    cmd: git clone https://github.com/rbenv/ruby-build.git $(rbenv root)/plugins/ruby-build
    creates: "{{ rbenv_root}}/plugins/ruby-build"
