---
- name: Install nvm
  command:
    cmd: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    creates: $HOME/.config/nvm

- name: symlink node to ~/.local/bin
  file:
    src: "{{ nvm_dir }}/versions/node/v{{ node_version }}/bin/node"
    dest: "$HOME/.local/bin/node"
    state: link

- name: symlink npm to ~/.local/bin
  file:
    src: "{{ nvm_dir }}/versions/node/v{{ node_version }}/bin/npm"
    dest: "$HOME/.local/bin/npm"
    state: link

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
    executable: "$HOME/.config/nvm/versions/node/v{{ node_version }}/bin/npm"
    state: present
  loop: "{{ npm_packages }}"
  loop_control:
    label: "{{ item }}"

- name: Install rbenv
  command:
    cmd: git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    creates: $HOME/.rbenv

- name: Create rbenv plugins dir
  command:
    cmd: mkdir -p $(rbenv root)/plugins
    creates: "{{ rbenv_root }}/plugins"

- name: Install ruby-build
  command:
    cmd: git clone https://github.com/rbenv/ruby-build.git $(rbenv root)/plugins/ruby-build
    creates: "{{ rbenv_root}}/plugins/ruby-build"
