- name: Symlink personal dotfiles
  ansible.builtin.command:
    argv:
      - stow
      - --dotfiles
      - git_config
  changed_when: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
