vim.api.nvim_create_user_command("DiffOrig", function()
  vim.cmd("vert new")
  vim.cmd("setlocal buftype=nofile")
  vim.cmd("read ++edit #")
  vim.cmd("0d_")
  vim.cmd("diffthis")
  vim.cmd("wincmd p")
  vim.cmd("diffthis")
end, { nargs = 0 })
