---
- name: Create $HOME/.venv folder
  command:
    cmd: mkdir $HOME/.venv
    creates: $HOME/.venv

- name: Create default venv
  command:
    cmd: /usr/bin/python3 -m venv $HOME/.venv/venv
    creates: $HOME/.venv/venv

- name: Install user packages
  pip: 
    name:
      - virtualenv
      - ipython
    extra_args: --user

- name: Install venv packages
  pip:
    name:
      - python-lsp-server
      - rope
      - pyflakes
      - mccabe
      - pycodestyle
      - pydocstyle
      - autopep8
      - yapf
      - pyls-flake8
      - pylsp-mypy
      - pyls-isort
      - python-lsp-black
      - pyls-memestra
      - pylsp-rope
      - pylint
      - black
      - compiledb
      - pre-commit
      - ipython
      - pandas
      - mypy
    virtualenv: "$HOME/.venv/venv"
