---
- name: Create $HOME/.venv folder
  ansible.builtin.file:
    path: $HOME/.venv
    state: directory
    mode: '0755'

- name: Install global pip packages
  ansible.builtin.pip:
    name:
      - compiledb
      - twine

- name: Install pipx packages
  community.general.pipx:
    name:
      - ipython
      - pipdeptree
      - poetry
      - pre-commit
      - tox

- name: Create default venv
  ansible.builtin.command:
    cmd: /usr/bin/python3 -m venv $HOME/.venv/venv
    creates: $HOME/.venv/venv

- name: Install venv packages
  ansible.builtin.pip:
    name:
      - compiledb
      - ipython
      - jupyterlab
      - matplotlib
      - mypy
      - notebook
      - numpy
      - pandas
      - pipx
      - pls
      - pre-commit
      - pydocstyle
      - pynvim
      - pytest
      - scikit-learn
      - tox
      - virtualenv
      - yapf
    virtualenv: "$HOME/.venv/venv"
