---
- name: Create $HOME/.venv folder
  file:
    path: $HOME/.venv
    state: directory

- name: Create default venv
  command:
    cmd: /usr/bin/python3 -m venv $HOME/.venv/venv
    creates: $HOME/.venv/venv

- name: Install venv packages
  pip:
    name:
      - autopep8
      - black
      - compiledb
      - ipython
      - jupyterlab
      - matplotlib
      - mccabe
      - mypy
      - notebook
      - pandas
      - pre-commit
      - pycodestyle
      - pydocstyle
      - pyflakes
      - pylint
      - pyls-flake8
      - pyls-isort
      - pyls-memestra
      - pylsp-mypy
      - pylsp-rope
      - pynvim
      - pytest
      - python-lsp-black
      - python-lsp-server
      - rope
      - scikit-learn
      - virtualenv
      - yapf
    virtualenv: "$HOME/.venv/venv"
