---
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpak_install_packages }}"
  loop_control:
    label: "{{ item }}"
