apt_packages:
  - build-essential
  - manpages-dev
  - virt-manager
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - bat
  - clang
  - clang-tools
  - cmake
  - curl
  - dconf-cli
  - eza
  - fd-find
  - libfontconfig1-dev
  - libfreetype6-dev
  - fzf
  - g++
  - gcc
  - gettext
  - libgif-dev
  - gimp
  - git
  - gitk
  - gnome-tweaks
  - libgnutls28-dev
  - libgtk2.0-dev
  - htop
  - libjansson-dev
  - libx11-dev
  - libxpm-dev
  - libgccjit-12-dev
  - libpng-dev
  - libtiff-dev
  - libtool
  - libvterm-dev
  - libxcb1-dev
  - libxkbcommon-dev
  - llvm
  - lua5.4
  - make
  - mise
  - nasm
  - libncurses-dev
  - ninja-build
  - perl
  - qemu-utils
  - ripgrep
  - rsync
  - ruby-dev
  - ruby-mdl
  - shellcheck
  - sqlite3
  - libsqlite3-dev
  - texinfo
  - util-linux
  - virtinst
  - zsh

rustup_version: "1.28.2"
rustup_target_map:
  x86_64: x86_64-unknown-linux-gnu
  aarch64: aarch64-unknown-linux-gnu
