dnf_packages:
  - '@C Development Tools and Libraries'
  - '@virtualization'
  - '@Development Tools'
  - bat
  - clang
  - clang-tools-extra
  - cmake
  - curl
  - dconf
  - eza
  - fd-find
  - fontconfig-devel
  - freetype-devel
  - fzf
  - g++
  - gcc
  - gettext
  - giflib-devel
  - gimp
  - git-core
  - gitk
  - glibc-gconv-extra
  - gnome-tweaks
  - gnutls-devel
  - gtk2-devel
  - htop
  - jansson-devel
  - java-11-openjdk-devel
  - libX11-devel
  - libXpm-devel
  - libgccjit-devel
  - libpng-devel
  - libstdc++-static
  - libtiff-devel
  - libtool
  - libvirt
  - libvterm
  - libxcb-devel
  - libxkbcommon-devel
  - llvm
  - lua
  - make
  - mise
  - nasm
  - ncurses-devel
  - ninja-build
  - perl-core
  - qemu-img
  - qemu-kvm
  - ripgrep
  - rsync
  - ruby-devel
  - shellcheck
  - sqlite
  - sqlite-devel
  - texinfo
  - util-linux-user
  - virt-install
  - virt-manager
  - zoxide
  - zsh

rustup_version: "1.28.2"
rustup_target_map:
  x86_64: x86_64-unknown-linux-gnu
  aarch64: aarch64-unknown-linux-gnu
