# setops
setopt INTERACTIVE_COMMENTS # allow comments even in interactive shells
unsetopt AUTO_CD            # assume cd if directory passed
unsetopt CORRECT            # try to correct spelling of commands
unsetopt CORRECT_ALL        # try to correct spelling of all arguments
setopt PROMPT_SUBST         # allow expansions in prompt (needed for __git_ps1)
setopt COMPLETE_IN_WORD     # allow tab completion in the middle of a word
setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
unsetopt FLOW_CONTROL       # disable C-s/C-q behavior


# history
HISTSIZE=1000000
SAVEHIST=1000000
setopt SHARE_HISTORY  # share history across multiple zsh sessions
setopt APPEND_HISTORY  # append to history
setopt INC_APPEND_HISTORY  # adds commands as they are typed, not at shell exit
setopt HIST_EXPIRE_DUPS_FIRST  # expire duplicates first
setopt HIST_IGNORE_DUPS  # do not store duplications
setopt HIST_FIND_NO_DUPS  # ignore duplicates when searching
setopt HIST_REDUCE_BLANKS  # removes blank lines from history
setopt EXTENDED_HISTORY  # Include more information about when the command was executed,
setopt HIST_IGNORE_SPACE  # Don't enter commands into history if they start with a space
setopt HIST_VERIFY  # nicer substitution commands


autoload -U colors && colors

source $ZDOTDIR/zsh_completion
source $ZDOTDIR/zsh_bindings
source $ZDOTDIR/zsh_prompt
source $ZDOTDIR/zsh_aliases
source $ZDOTDIR/zsh_functions
test -f $HOME/.zsh_local && source $HOME/.zsh_local

# vim as editor
export EDITOR="nvim"

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
