- name: Install devtools formulas
  community.general.homebrew:
    name:
      - ansible-language-server
      - ast-grep
      - atuin
      - autoconf
      - automake
      - bash
      - bash-language-server
      - bat
      - bfs
      - cloc
      - cmake
      - cmake-docs
      - colima
      - coreutils
      - csvlens
      - ctags
      - curl
      - difftastic
      - docker
      - docker-buildx
      - docker-completion
      - docker-compose
      - docker-credential-helper
      - dockerfile-language-server
      - eslint
      - eza
      - fd
      - fish
      - fzf
      - gcc
      - gettext
      - git
      - git-absorb
      - git-gui
      - git-lfs
      - gnutls
      - gopls
      - hadolint
      - helix
      - helm
      - helm-ls
      - imagemagick
      - jdtls
      - jless
      - jq
      - jsonlint
      - just
      - k9s
      - kubectx
      - kubernetes-cli
      - libgccjit
      - llvm
      - lua
      - lua-language-server
      - luajit
      - luarocks
      - markdownlint-cli
      - marksman
      - minikube
      - mise
      - mysql
      - ncdu
      - ninja
      - openjdk
      - perl
      - pipx
      - pixi
      - postgresql@17
      - prettier
      - rclone
      - redis
      - ripgrep
      - ruff
      - sd
      - shellcheck
      - sk
      - stow
      - stylua
      - taplo
      - tectonic
      - terraform-ls
      - the_silver_searcher
      - tig
      - tmux
      - tox
      - tree
      - tree-sitter
      - typescript-language-server
      - uv
      - virtualenv
      - vscode-langservers-extracted
      - vue-language-server
      - watch
      - watchexec
      - wcurl
      - wget
      - yaml-language-server
      - yamlfmt
      - yamllint
      - yq
      - zsh
      - zsh-async
      - zsh-autosuggestions
      - zsh-completions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
    state: present
    update_homebrew: true
    force_formula: true
