require("reload")
local focus = require("focus")

local browser = "firefox"
local terminal = "WezTerm"
local api_query = "Bruno"

hs.hotkey.bind({ "cmd", "shift" }, "a", function()
  focusandback("Safari")
end)
hs.hotkey.bind({ "cmd", "shift" }, "c", function()
  focusandback("Calendar")
end)
hs.hotkey.bind({ "cmd", "shift" }, "d", function()
  focusandback("DataGrip")
end)
hs.hotkey.bind({ "cmd", "shift" }, "f", function()
  focusandback(browser)
end)
hs.hotkey.bind({ "cmd", "shift" }, "g", function()
  focusandback("Google Chrome")
end)
hs.hotkey.bind({ "cmd", "shift" }, "j", function()
  focusandback(terminal)
end)
hs.hotkey.bind({ "cmd", "shift" }, "k", function()
  focusandback("PyCharm Professional Edition")
end)
hs.hotkey.bind({ "cmd", "shift" }, "m", function()
  focusandback("Mattermost")
end)
hs.hotkey.bind({ "cmd", "shift" }, "n", function()
  focusandback(api_query)
end)
hs.hotkey.bind({ "cmd", "shift" }, "o", function()
  focusandback("Microsoft Outlook")
end)
hs.hotkey.bind({ "cmd", "shift" }, "s", function()
  focusandback("Spotify")
end)
hs.hotkey.bind({ "cmd", "shift" }, ";", function()
  focusandback("Reminders")
end)
