- name: Update uv tool packages
  ansible.builtin.command:
    cmd: uv tool upgrade --all
- name: Update installed homebrew apps
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: ansible_facts['os_family'] == 'Darwin'
- name: Upgrade all casks
  community.general.homebrew_cask:
    upgrade_all: true
  when: ansible_facts['os_family'] == 'Darwin'
- name: Update submodules in $HOME/.dotfiles repo
  ansible.builtin.shell: |
    git submodule update --init --remote && git submodule update --recursive
- name: Run dnf upgrade
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_facts['pkg_mgr'] == 'dnf'
- name: Run apt upgrade
  become: true
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_facts['pkg_mgr'] == 'apt'
- name: Update installed nvim packages
  ansible.builtin.shell: |
    nvim --headless ':Lazy update' +qa
